# Generated by Django 3.1.2 on 2020-10-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Magazyn',
            new_name='Storage',
        ),
        migrations.DeleteModel(
            name='Produkt',
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.storage'),
        ),
    ]
